/*******************************************************************************
 * Copyright (c) 2010 - 2012 ACIN, Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann, Alois Zoitl, Ingo Hegny
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
#include "stringlist.h"

extern const CStringDictionary::TStringId g_nStringIdANY = 0;
extern const CStringDictionary::TStringId g_nStringIdANY_ADAPTER = 4;
extern const CStringDictionary::TStringId g_nStringIdANY_BIT = 16;
extern const CStringDictionary::TStringId g_nStringIdANY_ELEMENTARY = 24;
extern const CStringDictionary::TStringId g_nStringIdANY_INT = 39;
extern const CStringDictionary::TStringId g_nStringIdANY_MAGNITUDE = 47;
extern const CStringDictionary::TStringId g_nStringIdANY_NUM = 61;
extern const CStringDictionary::TStringId g_nStringIdANY_REAL = 69;
extern const CStringDictionary::TStringId g_nStringIdANY_STRING = 78;
extern const CStringDictionary::TStringId g_nStringIdARRAY = 89;
extern const CStringDictionary::TStringId g_nStringIdARTimeOut = 95;
extern const CStringDictionary::TStringId g_nStringIdATimeOut = 105;
extern const CStringDictionary::TStringId g_nStringIdBOOL = 114;
extern const CStringDictionary::TStringId g_nStringIdBYTE = 119;
extern const CStringDictionary::TStringId g_nStringIdCD = 124;
extern const CStringDictionary::TStringId g_nStringIdCDO = 127;
extern const CStringDictionary::TStringId g_nStringIdCLK = 131;
extern const CStringDictionary::TStringId g_nStringIdCMD_DOWN = 135;
extern const CStringDictionary::TStringId g_nStringIdCMD_UP = 144;
extern const CStringDictionary::TStringId g_nStringIdCNF = 151;
extern const CStringDictionary::TStringId g_nStringIdCNF_MSG = 155;
extern const CStringDictionary::TStringId g_nStringIdCNF_SET_TEMP = 163;
extern const CStringDictionary::TStringId g_nStringIdCNF_TEMP = 176;
extern const CStringDictionary::TStringId g_nStringIdCO = 185;
extern const CStringDictionary::TStringId g_nStringIdCOLD = 188;
extern const CStringDictionary::TStringId g_nStringIdCU = 193;
extern const CStringDictionary::TStringId g_nStringIdCUO = 196;
extern const CStringDictionary::TStringId g_nStringIdCV = 200;
extern const CStringDictionary::TStringId g_nStringIdCYCLE = 203;
extern const CStringDictionary::TStringId g_nStringIdD = 209;
extern const CStringDictionary::TStringId g_nStringIdDATE = 211;
extern const CStringDictionary::TStringId g_nStringIdDATE_AND_TIME = 216;
extern const CStringDictionary::TStringId g_nStringIdDEV_MGR = 230;
extern const CStringDictionary::TStringId g_nStringIdDINT = 238;
extern const CStringDictionary::TStringId g_nStringIdDLY = 243;
extern const CStringDictionary::TStringId g_nStringIdDST = 247;
extern const CStringDictionary::TStringId g_nStringIdDT = 251;
extern const CStringDictionary::TStringId g_nStringIdDWORD = 254;
extern const CStringDictionary::TStringId g_nStringIdEI = 260;
extern const CStringDictionary::TStringId g_nStringIdEI0 = 263;
extern const CStringDictionary::TStringId g_nStringIdEI1 = 267;
extern const CStringDictionary::TStringId g_nStringIdEI2 = 271;
extern const CStringDictionary::TStringId g_nStringIdEMB_RES = 275;
extern const CStringDictionary::TStringId g_nStringIdEO = 283;
extern const CStringDictionary::TStringId g_nStringIdEO0 = 286;
extern const CStringDictionary::TStringId g_nStringIdEO1 = 290;
extern const CStringDictionary::TStringId g_nStringIdEO2 = 294;
extern const CStringDictionary::TStringId g_nStringIdEO3 = 298;
extern const CStringDictionary::TStringId g_nStringIdERROR = 302;
extern const CStringDictionary::TStringId g_nStringIdE_CTD = 308;
extern const CStringDictionary::TStringId g_nStringIdE_CTU = 314;
extern const CStringDictionary::TStringId g_nStringIdE_CTUD = 320;
extern const CStringDictionary::TStringId g_nStringIdE_CYCLE = 327;
extern const CStringDictionary::TStringId g_nStringIdE_DELAY = 335;
extern const CStringDictionary::TStringId g_nStringIdE_DEMUX = 343;
extern const CStringDictionary::TStringId g_nStringIdE_D_FF = 351;
extern const CStringDictionary::TStringId g_nStringIdE_F_TRIG = 358;
extern const CStringDictionary::TStringId g_nStringIdE_MERGE = 367;
extern const CStringDictionary::TStringId g_nStringIdE_PERMIT = 375;
extern const CStringDictionary::TStringId g_nStringIdE_RDELAY = 384;
extern const CStringDictionary::TStringId g_nStringIdE_REND = 393;
extern const CStringDictionary::TStringId g_nStringIdE_RESTART = 400;
extern const CStringDictionary::TStringId g_nStringIdE_RS = 410;
extern const CStringDictionary::TStringId g_nStringIdE_RTimeOut = 415;
extern const CStringDictionary::TStringId g_nStringIdE_R_TRIG = 426;
extern const CStringDictionary::TStringId g_nStringIdE_SELECT = 435;
extern const CStringDictionary::TStringId g_nStringIdE_SPLIT = 444;
extern const CStringDictionary::TStringId g_nStringIdE_SR = 452;
extern const CStringDictionary::TStringId g_nStringIdE_SWITCH = 457;
extern const CStringDictionary::TStringId g_nStringIdE_TimeOut = 466;
extern const CStringDictionary::TStringId g_nStringIdF_TO_C_CONV2 = 476;
extern const CStringDictionary::TStringId g_nStringIdG = 489;
extern const CStringDictionary::TStringId g_nStringIdGEN_CLIENT = 491;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_DEMUX = 502;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_MUX = 514;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBL = 524;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBLISH = 533;
extern const CStringDictionary::TStringId g_nStringIdGEN_SERVER = 545;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBL = 556;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBSCRIBE = 565;
extern const CStringDictionary::TStringId g_nStringIdGET_TEMP = 579;
extern const CStringDictionary::TStringId g_nStringIdID = 588;
extern const CStringDictionary::TStringId g_nStringIdIND = 591;
extern const CStringDictionary::TStringId g_nStringIdINIT = 595;
extern const CStringDictionary::TStringId g_nStringIdINITO = 600;
extern const CStringDictionary::TStringId g_nStringIdINT = 606;
extern const CStringDictionary::TStringId g_nStringIdK = 610;
extern const CStringDictionary::TStringId g_nStringIdLD = 612;
extern const CStringDictionary::TStringId g_nStringIdLDO = 615;
extern const CStringDictionary::TStringId g_nStringIdLINT = 619;
extern const CStringDictionary::TStringId g_nStringIdLREAL = 624;
extern const CStringDictionary::TStringId g_nStringIdLWORD = 630;
extern const CStringDictionary::TStringId g_nStringIdMGR = 636;
extern const CStringDictionary::TStringId g_nStringIdMGR_FF = 640;
extern const CStringDictionary::TStringId g_nStringIdMGR_ID = 647;
extern const CStringDictionary::TStringId g_nStringIdPERMIT = 654;
extern const CStringDictionary::TStringId g_nStringIdPV = 661;
extern const CStringDictionary::TStringId g_nStringIdQ = 664;
extern const CStringDictionary::TStringId g_nStringIdQD = 666;
extern const CStringDictionary::TStringId g_nStringIdQI = 669;
extern const CStringDictionary::TStringId g_nStringIdQO = 672;
extern const CStringDictionary::TStringId g_nStringIdQU = 675;
extern const CStringDictionary::TStringId g_nStringIdR = 678;
extern const CStringDictionary::TStringId g_nStringIdREAD = 680;
extern const CStringDictionary::TStringId g_nStringIdREAL = 685;
extern const CStringDictionary::TStringId g_nStringIdREQ = 690;
extern const CStringDictionary::TStringId g_nStringIdRESP = 694;
extern const CStringDictionary::TStringId g_nStringIdRMT_RES = 699;
extern const CStringDictionary::TStringId g_nStringIdRO = 707;
extern const CStringDictionary::TStringId g_nStringIdRQST = 710;
extern const CStringDictionary::TStringId g_nStringIdRSP = 715;
extern const CStringDictionary::TStringId g_nStringIdS = 719;
extern const CStringDictionary::TStringId g_nStringIdSHOW_MSG = 721;
extern const CStringDictionary::TStringId g_nStringIdSHOW_SET_TEMP = 730;
extern const CStringDictionary::TStringId g_nStringIdSHOW_TEMP = 744;
extern const CStringDictionary::TStringId g_nStringIdSINT = 754;
extern const CStringDictionary::TStringId g_nStringIdSTART = 759;
extern const CStringDictionary::TStringId g_nStringIdSTATUS = 765;
extern const CStringDictionary::TStringId g_nStringIdSTOP = 772;
extern const CStringDictionary::TStringId g_nStringIdSTRING = 777;
extern const CStringDictionary::TStringId g_nStringIdSWITCHsim = 784;
extern const CStringDictionary::TStringId g_nStringIdTEMP = 794;
extern const CStringDictionary::TStringId g_nStringIdTEMPERATUREsim = 799;
extern const CStringDictionary::TStringId g_nStringIdTI = 814;
extern const CStringDictionary::TStringId g_nStringIdTIME = 817;
extern const CStringDictionary::TStringId g_nStringIdTIME_OF_DAY = 822;
extern const CStringDictionary::TStringId g_nStringIdTimeOut = 834;
extern const CStringDictionary::TStringId g_nStringIdTimeOutSocket = 842;
extern const CStringDictionary::TStringId g_nStringIdUDINT = 856;
extern const CStringDictionary::TStringId g_nStringIdUINT = 862;
extern const CStringDictionary::TStringId g_nStringIdULINT = 867;
extern const CStringDictionary::TStringId g_nStringIdUSINT = 873;
extern const CStringDictionary::TStringId g_nStringIdWARM = 879;
extern const CStringDictionary::TStringId g_nStringIdWORD = 884;
extern const CStringDictionary::TStringId g_nStringIdWSTRING = 889;
extern const CStringDictionary::TStringId g_nStringIdZONE_SET_TEMPERATURE = 897;
extern const CStringDictionary::TStringId g_nStringIdZONE_TEMPERATURE = 918;
extern const CStringDictionary::TStringId g_nStringIdZ_CONTROLLER3 = 935;
extern const CStringDictionary::TStringId g_nStringIdZ_DISPLAY3 = 949;
extern const CStringDictionary::TStringId g_nStringIdaddress = 960;
extern const CStringDictionary::TStringId g_nStringIderror_code = 968;
extern const CStringDictionary::TStringId g_nStringIdin = 979;
extern const CStringDictionary::TStringId g_nStringIdmsg = 982;
extern const CStringDictionary::TStringId g_nStringIdparams = 986;
extern const CStringDictionary::TStringId g_nStringIdport = 993;
extern const CStringDictionary::TStringId g_nStringIdset_temp = 998;
extern const CStringDictionary::TStringId g_nStringIdset_zone_temp = 1007;
extern const CStringDictionary::TStringId g_nStringIdtemp = 1021;
extern const CStringDictionary::TStringId g_nStringIdtemp_C = 1026;
extern const CStringDictionary::TStringId g_nStringIdtemp_F = 1033;
extern const CStringDictionary::TStringId g_nStringIdwARM = 1040;
extern const CStringDictionary::TStringId g_nStringIdzone = 1045;
extern const CStringDictionary::TStringId g_nStringIdzone_msg = 1050;
extern const CStringDictionary::TStringId g_nStringIdzone_temp = 1059;
extern const CStringDictionary::TStringId g_nStringIdNextFreeId = 1069;
extern const unsigned int cg_nNumOfConstStrings = 154;


#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  CStringDictionary::TStringId CStringDictionary::scm_aunIdList[cg_unFORTE_StringDictInitialMaxNrOfStrings]
#else
  const CStringDictionary::TStringId CStringDictionary::scm_aunIdList[] 
#endif
  = {0, 4, 16, 24, 39, 47, 61, 69, 78, 89, 95, 105, 114, 119, 124, 127, 131, 135, 144, 151, 155, 163, 176, 185, 188, 193, 196, 200, 203, 209, 211, 216, 230, 238, 243, 247, 251, 254, 260, 263, 267, 271, 275, 283, 286, 290, 294, 298, 302, 308, 314, 320, 327, 335, 343, 351, 358, 367, 375, 384, 393, 400, 410, 415, 426, 435, 444, 452, 457, 466, 476, 489, 491, 502, 514, 524, 533, 545, 556, 565, 579, 588, 591, 595, 600, 606, 610, 612, 615, 619, 624, 630, 636, 640, 647, 654, 661, 664, 666, 669, 672, 675, 678, 680, 685, 690, 694, 699, 707, 710, 715, 719, 721, 730, 744, 754, 759, 765, 772, 777, 784, 794, 799, 814, 817, 822, 834, 842, 856, 862, 867, 873, 879, 884, 889, 897, 918, 935, 949, 960, 968, 979, 982, 986, 993, 998, 1007, 1021, 1026, 1033, 1040, 1045, 1050, 1059};

#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  char CStringDictionary::scm_acConstStringBuf[cg_unFORTE_StringDictInitialStringBufSize]
#else
  const char CStringDictionary::scm_acConstStringBuf[] 
#endif
  = {"ANY\0ANY_ADAPTER\0ANY_BIT\0ANY_ELEMENTARY\0ANY_INT\0ANY_MAGNITUDE\0ANY_NUM\0ANY_REAL\0ANY_STRING\0ARRAY\0ARTimeOut\0ATimeOut\0BOOL\0BYTE\0CD\0CDO\0CLK\0CMD_DOWN\0CMD_UP\0CNF\0CNF_MSG\0CNF_SET_TEMP\0CNF_TEMP\0CO\0COLD\0CU\0CUO\0CV\0CYCLE\0D\0DATE\0DATE_AND_TIME\0DEV_MGR\0DINT\0DLY\0DST\0DT\0DWORD\0EI\0EI0\0EI1\0EI2\0EMB_RES\0EO\0EO0\0EO1\0EO2\0EO3\0ERROR\0E_CTD\0E_CTU\0E_CTUD\0E_CYCLE\0E_DELAY\0E_DEMUX\0E_D_FF\0E_F_TRIG\0E_MERGE\0E_PERMIT\0E_RDELAY\0E_REND\0E_RESTART\0E_RS\0E_RTimeOut\0E_R_TRIG\0E_SELECT\0E_SPLIT\0E_SR\0E_SWITCH\0E_TimeOut\0F_TO_C_CONV2\0G\0GEN_CLIENT\0GEN_E_DEMUX\0GEN_E_MUX\0GEN_PUBL\0GEN_PUBLISH\0GEN_SERVER\0GEN_SUBL\0GEN_SUBSCRIBE\0GET_TEMP\0ID\0IND\0INIT\0INITO\0INT\0K\0LD\0LDO\0LINT\0LREAL\0LWORD\0MGR\0MGR_FF\0MGR_ID\0PERMIT\0PV\0Q\0QD\0QI\0QO\0QU\0R\0READ\0REAL\0REQ\0RESP\0RMT_RES\0RO\0RQST\0RSP\0S\0SHOW_MSG\0SHOW_SET_TEMP\0SHOW_TEMP\0SINT\0START\0STATUS\0STOP\0STRING\0SWITCHsim\0TEMP\0TEMPERATUREsim\0TI\0TIME\0TIME_OF_DAY\0TimeOut\0TimeOutSocket\0UDINT\0UINT\0ULINT\0USINT\0WARM\0WORD\0WSTRING\0ZONE_SET_TEMPERATURE\0ZONE_TEMPERATURE\0Z_CONTROLLER3\0Z_DISPLAY3\0address\0error_code\0in\0msg\0params\0port\0set_temp\0set_zone_temp\0temp\0temp_C\0temp_F\0wARM\0zone\0zone_msg\0zone_temp\0"};

 
