/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdCNF_TEMP;
 extern const CStringDictionary::TStringId g_nStringIdERROR;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdINT;
 extern const CStringDictionary::TStringId g_nStringIdLINT;
 extern const CStringDictionary::TStringId g_nStringIdREAD;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTEMPERATUREsim;
 extern const CStringDictionary::TStringId g_nStringIdTI;
 extern const CStringDictionary::TStringId g_nStringIdaddress;
 extern const CStringDictionary::TStringId g_nStringIderror_code;
 extern const CStringDictionary::TStringId g_nStringIdport;
 extern const CStringDictionary::TStringId g_nStringIdtemp_F;
 extern const CStringDictionary::TStringId g_nStringIdzone;

