/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdCMD_DOWN;
 extern const CStringDictionary::TStringId g_nStringIdCMD_UP;
 extern const CStringDictionary::TStringId g_nStringIdCNF_MSG;
 extern const CStringDictionary::TStringId g_nStringIdCNF_SET_TEMP;
 extern const CStringDictionary::TStringId g_nStringIdCNF_TEMP;
 extern const CStringDictionary::TStringId g_nStringIdCYCLE;
 extern const CStringDictionary::TStringId g_nStringIdERROR;
 extern const CStringDictionary::TStringId g_nStringIdGET_TEMP;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINT;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTEMP;
 extern const CStringDictionary::TStringId g_nStringIdTI;
 extern const CStringDictionary::TStringId g_nStringIdZONE_SET_TEMPERATURE;
 extern const CStringDictionary::TStringId g_nStringIdZONE_TEMPERATURE;
 extern const CStringDictionary::TStringId g_nStringIdZ_CONTROLLER3;
 extern const CStringDictionary::TStringId g_nStringIderror_code;
 extern const CStringDictionary::TStringId g_nStringIdset_zone_temp;
 extern const CStringDictionary::TStringId g_nStringIdtemp_C;
 extern const CStringDictionary::TStringId g_nStringIdzone_msg;
 extern const CStringDictionary::TStringId g_nStringIdzone_temp;

