/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdINT;
 extern const CStringDictionary::TStringId g_nStringIdLINT;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdSHOW_MSG;
 extern const CStringDictionary::TStringId g_nStringIdSHOW_SET_TEMP;
 extern const CStringDictionary::TStringId g_nStringIdSHOW_TEMP;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTI;
 extern const CStringDictionary::TStringId g_nStringIdZ_DISPLAY3;
 extern const CStringDictionary::TStringId g_nStringIdaddress;
 extern const CStringDictionary::TStringId g_nStringIdmsg;
 extern const CStringDictionary::TStringId g_nStringIdport;
 extern const CStringDictionary::TStringId g_nStringIdset_temp;
 extern const CStringDictionary::TStringId g_nStringIdtemp;
 extern const CStringDictionary::TStringId g_nStringIdzone;

